CREATE TABLE IF NOT EXISTS users
(
    id CHARACTER VARYING(100) NOT NULL UNIQUE,
    status CHARACTER VARYING(100) NOT NULL,
    first_name CHARACTER VARYING(100) NOT NULL,
    username CHARACTER VARYING(100) NULL,
    language_code CHARACTER VARYING(100) NOT NULL,
    week_starts_on NUMERIC(1,0) NOT NULL,
    time_zone CHARACTER VARYING(100) NOT NULL,
    quota INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NULL,
    deleted_at TIMESTAMPTZ NULL
);